default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>

development:
  primary:
    <<: *default
    database: blog_development

  queue:
    <<: *default
    database: blog_development_queue
    migrations_paths: db/queue_migrate

test:
  primary:
    <<: *default
    database: blog_test

  queue:
    <<: *default
    database: blog_test_queue
    migrations_paths: db/queue_migrate

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

  queue:
    <<: *default
    url: <%= ENV['QUEUE_DATABASE_URL'] || ENV['DATABASE_URL'] %>
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

  cache:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
